name: DEV-Edu-Mirror
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Sync repositories
      run: |
        chmod +x sync_repos.sh
        ./sync_repos.sh

    - name: Clean up
      run: |
        rm -rf "$TEMP_DIR"
