name: DEV-Edu-Mirror
on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 */12 * * *
  workflow_dispatch: {}
jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        with:
          source-repo: "git@gitee.com:dev-edu/CSS.git"
          destination-repo: "git@github.com:DEV-Edu-Mirror/CSS.git"
      